[package]
name = "testquorum-runner"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
testquorum-api = { path = "../testquorum-api" }
testquorum-config = { path = "../testquorum-config" }
thiserror = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "1.0"
which = "8"
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "process", "fs", "sync"] }
tokio-stream = "0.1"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.10"
base64 = "0.22"
sha2 = "0.10"
uuid = { version = "1", features = ["v7"] }
git2 = { version = "0.20", default-features = false }
tempfile = "3"
