[package]
name = "testquorum-api"
version = "0.1.172"
edition.workspace = true
license.workspace = true

description = "Progenitor generated Rust interface to api.testquorum.dev"

[dependencies]
progenitor = "0.13"
reqwest = { version = "0.13", default-features = false, features = ["json", "stream", "rustls"] }
serde = { version = "1.0", features = ["derive"] }
