name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  merge_group:
  schedule:
    - cron: '24 * * * *'
  workflow_dispatch:

jobs:
  nix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Setup Nix S3 cache
        uses: testquorum/nix-s3-generations@45aa2ff2b0df67b5f48a1b710c574c754f08a0c7 # v0.1.4
        with:
          s3-endpoint: ba58a56742691d9efc310cca51093d04.r2.cloudflarestorage.com
          bucket: testquorum-nix-public
          region: auto
          aws-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          public-key: "nixcache.testquorum.dev-1:aS+CJF8O8Ebirc6hypMfq/061h5TJlbsej1+zUJHPec="
          private-key: ${{ secrets.NIX_SIGNING_KEY }}

      - name: Enter CI devShell
        uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1
        with:
          arguments: .#ci

      - name: Build and test
        uses: testquorum/action@3db603cb6367a5777dd7eff11d7df7880ef56b32 # main
        with:
          version: ${{ github.sha }}
          flake-ref: .#testquorum-runner
          token: ${{ secrets.TESTQUORUM_AUTH_TOKEN }}

